import Image from "next/image";
import styles from "../styles/page.module.css";
import Link from "next/link";
// import type { Metadata } from "next";
import { useRouter } from "next/router";
import { MainLayout } from "@/components/layouts";

import { NextPageWithLayout } from "@/models";

// export const metadata: Metadata = {
//     title: "learn-nextjs",
//     description: "Generated by create next app",
//   };

  
const  Home: NextPageWithLayout = () => {


        const router = useRouter();
     
        function goToDetailPage () {
            router.push({
                pathname: '/posts/[postId]',
                query: {
                    postId: 123,
                    ref: 'social'
                }
            })
        }
      
    return (
     
      <div className={styles.page}>
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol>
            <li>
              Get started by editing <code>page/page/tsx</code>.
            </li>
            <li>hello.</li>
            <li><Link href={'about'}>about page</Link></li>
            <li><Link href={'/posts'}>posts page</Link></li>
            <li><Link href={'/posts/create'}>posts list page</Link></li>
          </ol>
          <button  onClick={goToDetailPage}>Go to PostDetailPae</button>
  
          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Deploy now
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Read our docs
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
      </div>
     
    );
  }
  Home.Layout = MainLayout

export default Home 