// import type { Metadata } from "next";
import { Seo } from "@/components/common/SEO";
import { FeaturedWork, HeroSection, RecentPosts } from "@/components/home";
import { MainLayout } from "@/components/layouts";
import { NextPageWithLayout } from "@/models";
import { Box } from "@mui/material";

// export const metadata: Metadata = {
//     title: "learn-nextjs",
//     description: "Generated by create next app",
//   };

  
const  Home: NextPageWithLayout = () => {

      
    return (
     
      <Box>
          <Seo data={{
            title: 'Learn NextJs with Me | ProCode',
            description: 'Step by step tutorials to build a full CRUD website using NextJs for Beginner.  Eszy, Free and Interesting',
            url: 'https://learn-nextjs-route-page.vercel.app',
            thumbnaiUrl: 'https://res.cloudinary.com/dr3f1lp7e/image/upload/v1743069542/igmeTele_axfter.jpg',
          }}/>
          <HeroSection/>
          <RecentPosts/>
          <FeaturedWork/>
         
      </Box>

    );
  }
  Home.Layout = MainLayout

export default Home 