// import type { Metadata } from "next";
import { HeroSection } from "@/components/home";
import { MainLayout } from "@/components/layouts";
import { NextPageWithLayout } from "@/models";
import { Box } from "@mui/material";

// export const metadata: Metadata = {
//     title: "learn-nextjs",
//     description: "Generated by create next app",
//   };

  
const  Home: NextPageWithLayout = () => {

      
    return (
     
      <Box>
       
          <HeroSection/>
          
      </Box>

    );
  }
  Home.Layout = MainLayout

export default Home 